export type DocumentType =
  | 'mutual_nda'
  | 'baa'
  | 'csa'
  | 'dpa'
  | 'partnership'
  | 'pilot'
  | 'psa'
  | 'sla'
  | 'software_license'
  | 'ai_addendum'
  | 'design_partner';

export const DOCUMENT_DISPLAY_NAMES: Record<DocumentType, string> = {
  mutual_nda: 'Mutual Non-Disclosure Agreement',
  baa: 'Business Associate Agreement',
  csa: 'Cloud Service Agreement',
  dpa: 'Data Processing Agreement',
  partnership: 'Partnership Agreement',
  pilot: 'Pilot Agreement',
  psa: 'Professional Services Agreement',
  sla: 'Service Level Agreement',
  software_license: 'Software License Agreement',
  ai_addendum: 'AI Addendum',
  design_partner: 'Design Partner Agreement',
};

// Template files served from /templates/ in the Next.js public directory.
// Each document type maps to one or two template file paths.
// For NDA we use a dedicated preview component instead.
export const TEMPLATE_PATHS: Partial<Record<DocumentType, string[]>> = {
  baa: ['/templates/BAA.md'],
  csa: ['/templates/CSA.md'],
  dpa: ['/templates/DPA.md'],
  partnership: ['/templates/Partnership-Agreement.md'],
  pilot: ['/templates/Pilot-Agreement.md'],
  psa: ['/templates/psa.md'],
  sla: ['/templates/sla.md'],
  software_license: ['/templates/Software-License-Agreement.md'],
  ai_addendum: ['/templates/AI-Addendum.md'],
  design_partner: ['/templates/design-partner-agreement.md'],
};

// Maps template variable names (as they appear in <span class="keyterms_link">)
// to camelCase field keys used in form data.
export const VARIABLE_MAPS: Partial<Record<DocumentType, Record<string, string>>> = {
  baa: {
    'Provider': 'provider',
    'Company': 'company',
    'BAA Effective Date': 'baaEffectiveDate',
    'Agreement': 'agreement',
    'Breach Notification Period': 'breachNotificationPeriod',
    'Limitations': 'limitations',
  },
  csa: {
    'Provider': 'provider',
    'Customer': 'customer',
    'Effective Date': 'effectiveDate',
    'Governing Law': 'governingLaw',
    'Chosen Courts': 'chosenCourts',
    'General Cap Amount': 'generalCapAmount',
    'Subscription Period': 'subscriptionPeriod',
    'Order Date': 'orderDate',
    'Technical Support': 'technicalSupport',
    'Use Limitations': 'useLimitations',
    'Payment Process': 'paymentProcess',
    'Non-Renewal Notice Date': 'nonRenewalNoticeDate',
    'Increased Claims': 'increasedClaims',
    'Increased Cap Amount': 'increasedCapAmount',
    'Unlimited Claims': 'unlimitedClaims',
    'Provider Covered Claims': 'providerCoveredClaims',
    'Customer Covered Claims': 'customerCoveredClaims',
    'Additional Warranties': 'additionalWarranties',
    'DPA': 'dpa',
  },
  dpa: {
    'Provider': 'provider',
    'Customer': 'customer',
    'Agreement': 'agreement',
    'Categories of Personal Data': 'categoriesOfPersonalData',
    'Categories of Data Subjects': 'categoriesOfDataSubjects',
    'Special Category Data': 'specialCategoryData',
    'Special Category Data Restrictions or Safeguards': 'specialCategoryDataRestrictions',
    'Frequency of Transfer': 'frequencyOfTransfer',
    'Nature and Purpose of Processing': 'natureAndPurposeOfProcessing',
    'Duration of Processing': 'durationOfProcessing',
    'Approved Subprocessors': 'approvedSubprocessors',
    'Governing Member State': 'governingMemberState',
    'Security Policy': 'securityPolicy',
    'Provider Security Contact': 'providerSecurityContact',
  },
  partnership: {
    'Company': 'company',
    'Partner': 'partner',
    'Effective Date': 'effectiveDate',
    'Governing Law': 'governingLaw',
    'Chosen Courts': 'chosenCourts',
    'Obligations': 'obligations',
    'Territory': 'territory',
    'End Date': 'endDate',
    'General Cap Amount': 'generalCapAmount',
    'Payment Process': 'paymentProcess',
    'Payment Schedule': 'paymentSchedule',
    'Brand Guidelines': 'brandGuidelines',
    'Increased Claims': 'increasedClaims',
    'Increased Cap Amount': 'increasedCapAmount',
    'Unlimited Claims': 'unlimitedClaims',
    'Company Covered Claim': 'companyCoveredClaim',
    'Partner Covered Claims': 'partnerCoveredClaims',
    'Additional Warranties': 'additionalWarranties',
    'DPA': 'dpa',
  },
  pilot: {
    'Provider': 'provider',
    'Customer': 'customer',
    'Pilot Period': 'pilotPeriod',
    'Effective Date': 'effectiveDate',
    'Governing Law': 'governingLaw',
    'Chosen Courts': 'chosenCourts',
    'General Cap Amount': 'generalCapAmount',
    'Notice Address': 'noticeAddress',
  },
  psa: {
    'Provider': 'provider',
    'Customer': 'customer',
    'Effective Date': 'effectiveDate',
    'Governing Law': 'governingLaw',
    'Chosen Courts': 'chosenCourts',
    'Deliverables': 'deliverables',
    'Fees': 'fees',
    'SOW Term': 'sowTerm',
    'General Cap Amount': 'generalCapAmount',
    'Customer Policies': 'customerPolicies',
    'Insurance Minimums': 'insuranceMinimums',
    'Rejection Period': 'rejectionPeriod',
    'Resubmission Period': 'resubmissionPeriod',
    'Customer Obligations': 'customerObligations',
    'Payment Period': 'paymentPeriod',
    'Increased Claims': 'increasedClaims',
    'Increased Cap Amount': 'increasedCapAmount',
    'Unlimited Claims': 'unlimitedClaims',
    'Provider Covered Claims': 'providerCoveredClaims',
    'Customer Covered Claims': 'customerCoveredClaims',
    'Additional Warranties': 'additionalWarranties',
    'DPA': 'dpa',
    'Security Policy': 'securityPolicy',
  },
  sla: {
    'Provider': 'provider',
    'Customer': 'customer',
    'Target Uptime': 'targetUptime',
    'Target Response Time': 'targetResponseTime',
    'Support Channel': 'supportChannel',
    'Uptime Credit': 'uptimeCredit',
    'Response Time Credit': 'responseTimeCredit',
    'Subscription Period': 'subscriptionPeriod',
    'Scheduled Downtime': 'scheduledDowntime',
  },
  software_license: {
    'Provider': 'provider',
    'Customer': 'customer',
    'Effective Date': 'effectiveDate',
    'Governing Law': 'governingLaw',
    'Chosen Courts': 'chosenCourts',
    'Subscription Period': 'subscriptionPeriod',
    'Permitted Uses': 'permittedUses',
    'License Limits': 'licenseLimits',
    'Payment Process': 'paymentProcess',
    'Order Date': 'orderDate',
    'Warranty Period': 'warrantyPeriod',
    'Deletion Procedure': 'deletionProcedure',
    'Non-Renewal Notice Date': 'nonRenewalNoticeDate',
    'General Cap Amount': 'generalCapAmount',
    'Increased Claims': 'increasedClaims',
    'Increased Cap Amount': 'increasedCapAmount',
    'Unlimited Claims': 'unlimitedClaims',
    'Provider Covered Claims': 'providerCoveredClaims',
    'Customer Covered Claims': 'customerCoveredClaims',
    'Additional Warranties': 'additionalWarranties',
  },
  ai_addendum: {
    'Provider': 'provider',
    'Customer': 'customer',
    'Training Data': 'trainingData',
    'Training Purposes': 'trainingPurposes',
    'Training Restrictions': 'trainingRestrictions',
    'Improvement Restrictions': 'improvementRestrictions',
  },
  design_partner: {
    'Provider': 'provider',
    'Partner': 'partner',
    'Term': 'term',
    'Effective Date': 'effectiveDate',
    'Governing Law': 'governingLaw',
    'Chosen Courts': 'chosenCourts',
    'Program': 'program',
    'Notice Address': 'noticeAddress',
    'Fees': 'fees',
  },
};

// Default form data per document type
export const DEFAULT_FORM_DATA: Record<DocumentType, Record<string, string>> = {
  mutual_nda: {
    party1Company: '',
    party1Name: '',
    party1Title: '',
    party1Address: '',
    party1Date: '',
    party2Company: '',
    party2Name: '',
    party2Title: '',
    party2Address: '',
    party2Date: '',
    purpose: 'Evaluating whether to enter into a business relationship with the other party.',
    effectiveDate: '',
    mndaTermType: 'expires',
    mndaTermYears: '1',
    confidentialityTermType: 'period',
    confidentialityTermYears: '1',
    governingLaw: '',
    jurisdiction: '',
    modifications: '',
  },
  baa: {
    provider: '',
    company: '',
    baaEffectiveDate: '',
    agreement: '',
    breachNotificationPeriod: '',
    limitations: '',
  },
  csa: {
    provider: '',
    customer: '',
    effectiveDate: '',
    governingLaw: '',
    chosenCourts: '',
    generalCapAmount: '',
    subscriptionPeriod: '',
    orderDate: '',
    technicalSupport: '',
    useLimitations: '',
    paymentProcess: '',
    nonRenewalNoticeDate: '',
    increasedClaims: '',
    increasedCapAmount: '',
    unlimitedClaims: '',
    providerCoveredClaims: '',
    customerCoveredClaims: '',
    additionalWarranties: '',
    dpa: '',
  },
  dpa: {
    provider: '',
    customer: '',
    agreement: '',
    categoriesOfPersonalData: '',
    categoriesOfDataSubjects: '',
    natureAndPurposeOfProcessing: '',
    durationOfProcessing: '',
    specialCategoryData: '',
    specialCategoryDataRestrictions: '',
    frequencyOfTransfer: '',
    approvedSubprocessors: '',
    governingMemberState: '',
    securityPolicy: '',
    providerSecurityContact: '',
  },
  partnership: {
    company: '',
    partner: '',
    effectiveDate: '',
    governingLaw: '',
    chosenCourts: '',
    obligations: '',
    territory: '',
    endDate: '',
    generalCapAmount: '',
    paymentProcess: '',
    paymentSchedule: '',
    brandGuidelines: '',
    increasedClaims: '',
    increasedCapAmount: '',
    unlimitedClaims: '',
    companyCoveredClaim: '',
    partnerCoveredClaims: '',
    additionalWarranties: '',
    dpa: '',
  },
  pilot: {
    provider: '',
    customer: '',
    pilotPeriod: '',
    effectiveDate: '',
    governingLaw: '',
    chosenCourts: '',
    generalCapAmount: '',
    noticeAddress: '',
  },
  psa: {
    provider: '',
    customer: '',
    effectiveDate: '',
    governingLaw: '',
    chosenCourts: '',
    deliverables: '',
    fees: '',
    sowTerm: '',
    generalCapAmount: '',
    customerPolicies: '',
    insuranceMinimums: '',
    rejectionPeriod: '',
    resubmissionPeriod: '',
    customerObligations: '',
    paymentPeriod: '',
    increasedClaims: '',
    increasedCapAmount: '',
    unlimitedClaims: '',
    providerCoveredClaims: '',
    customerCoveredClaims: '',
    additionalWarranties: '',
    dpa: '',
    securityPolicy: '',
  },
  sla: {
    provider: '',
    customer: '',
    parentAgreement: '',
    targetUptime: '',
    targetResponseTime: '',
    supportChannel: '',
    uptimeCredit: '',
    responseTimeCredit: '',
    subscriptionPeriod: '',
    scheduledDowntime: '',
  },
  software_license: {
    provider: '',
    customer: '',
    effectiveDate: '',
    governingLaw: '',
    chosenCourts: '',
    subscriptionPeriod: '',
    permittedUses: '',
    licenseLimits: '',
    paymentProcess: '',
    orderDate: '',
    warrantyPeriod: '',
    deletionProcedure: '',
    nonRenewalNoticeDate: '',
    generalCapAmount: '',
    increasedClaims: '',
    increasedCapAmount: '',
    unlimitedClaims: '',
    providerCoveredClaims: '',
    customerCoveredClaims: '',
    additionalWarranties: '',
  },
  ai_addendum: {
    provider: '',
    customer: '',
    parentAgreement: '',
    trainingData: '',
    trainingPurposes: '',
    trainingRestrictions: '',
    improvementRestrictions: '',
  },
  design_partner: {
    provider: '',
    partner: '',
    effectiveDate: '',
    term: '',
    governingLaw: '',
    chosenCourts: '',
    program: '',
    noticeAddress: '',
    fees: '',
  },
};
